### ISSUE TITLE
RAM usage problem

### ISSUE THREAD

**Issue by weak-orange-wind** [openai/random-network-distillation#14]
I ran `python run_atari.py --ext_coeff 0.0 --int_coeff 1.0 --gamma_ext 0.999 --num_env 32` on a GTX 1080TI machine. In the beginning, it works well. But the memory(not GPU memory) usage keep improving as the program running. Finally it ran out of my 128G RAM and 32GB swap space and crashed. Any suggestions about this?

**Comment by weak-orange-wind** [comment]
This problem has been solved by using numpy==1.13

**Comment by azouaoui-cv** [comment]
Hey, did you get any good results/replays using the internal reward only?

**Comment by weak-orange-wind** [comment]
> 
> 
> Hey, did you get any good results/replays using the internal reward only?

Not yet

**Comment by jzstudent** [comment]
> This problem has been solved by using numpy==1.13

hey，I also meet this problem，my swap crashed after the program begining about 6 hours，I found using numpy==1.13 did not work. Do u have other suggestion?
